### ISSUE TITLE
[ UI/UX task ] Create a beautiful and simple good image for Readme.md 

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/Trading-Bot#1]
We have two images: main.png and link.png.
We want to redesign them from scratch.
Before submitting any changes, let's discuss if the redesign is necessary.
If we agree it's needed, we'll approve your pull request.

**Comment by Aryan-Chharia** [comment]
Hi, I am a contributor in GSSoC'24. I want to work on this issue. Could you assign this to me?

**Comment by hasmithagunda123** [comment]
Hi, I am a contributor in gssoc '24 , I would like to work on thic issue as i have expirence in frontend , could you assign this task to me

**Comment by Shivani-Sharma-23** [comment]
Hi ! Please assign this task to me . You can my readme's as well and i can also redesign images also.

**Comment by hasmithagunda123** [comment]
Hello I am good at the frontend part please assign this issue to me

**Comment by sleathblack007** [comment]
Hi, I am a contributor in GSSoC'24. I want to work on this issue. Could you assign this to me?

**Comment by Ayushpanditmoto** [comment]
@Shivani-Sharma-23  i am assigning this to you i found your github profile good

**Comment by Shivani-Sharma-23** [comment]
thank you . Check the pull request done some changes to readme
