### ISSUE TITLE
working on LSTM RNNs

### ISSUE THREAD

**Issue by nagamukesh** [Ayushpanditmoto/Trading-Bot#15]
I think it would be great to consider Long Short Term Recurral Neural Networks to get real-time info about the stock markets as it is a very powerful sequence model
please assign any issue related to this to me under gssoc 2024
I have a good knowledge over machine learning and deep learning

**Comment by Jashwanth05** [comment]
I have good knowledge regarding machine learning please assign this to me.

**Comment by aviralgarg05** [comment]
I have good knowledge about training lstm RNNs. I have worked on a similar project and has a good hand on it.

**Comment by Geetika2274** [comment]
Working on LSTM RNNs (long Short Term Memory Recurrent Nueural Network) would to be great opportunity to showcase my skills. 
Approach: 1.Describe training process.
                  2.Using Applications of Neural Network.

Assign any issue related to the LSTM RNNs, i will work on it.

**Comment by Kkartik14** [comment]
@Ayushpanditmoto  Can you please assign this to me
I have a decent amount of experience with NLP related stuff
