### ISSUE TITLE
ARIMA modelling

### ISSUE THREAD

**Issue by bansaldhruv20** [Ayushpanditmoto/Trading-Bot#22]
For the prediction of future trends and datasets, Arima modeling can be considered in action
Under Gssoc'24, assign this issue to me

**Comment by Hetul16** [comment]
Solution:
With prior internship experience in ARIMA modeling for time series analysis, I'm adept at forecasting future values and identifying trends. My responsibilities included data preprocessing, model selection, parameter tuning, and performance evaluation. This background equips me to effectively apply ARIMA modeling to analyze road scenes for animal detection, enhancing road safety.
As a part of GSSOC'24 assign this task to me!!

**Comment by Ayushpanditmoto** [comment]
@Hetul16 @bansaldhruv20  explain me more

**Comment by Hetul16** [comment]
It's a statistical model used for analyzing and forecasting time-series data. Time series data is just a sequence of data points collected or recorded over time, like stock prices, weather patterns, or sales figures.When you use an ARIMA model with a dataset like stock prices, it helps you understand patterns and predict future trends in stock prices.and i worked on the stock price Prediction model using the ARIMA model. So I have a basic understanding of this model, how it works, and all that!!!

**Comment by Ayushpanditmoto** [comment]
@Hetul16 can this help in predicting next candle ??

**Comment by Hetul16** [comment]
Yes, it is helpful but for that we have to have proper dataset In which all the required information is there

**Comment by Ayushpanditmoto** [comment]
@Hetul16 we have huge datasets

**Comment by Yatharth31** [comment]
I think we should try LSTM cause
ARIMA requires a series of parameters (p,q,d) which must be calculated based on data, while LSTM does not require setting such parameters. Also few research paper suggest that LSTM outperforms ARIMA for longer duration of time, but ARIMA works better for short term predictions.
