### ISSUE TITLE
Implementing Machine Learning for Trading Pattern Recognition using Technical Analysis 

### ISSUE THREAD

**Issue by RishabTR** [Ayushpanditmoto/Trading-Bot#26]
_Approach:_

**Identify Support and Resistance Levels:**

1. Implement a method to mark previous support and resistance levels.
2. Store these levels in a stack to track the last resistance or support level.

Pattern Recognition:

1. Recognize important candlestick patterns such as double tops, double bottoms, dojis, hammers, inverted hammers, etc.

**Prediction:**

1. Utilize the identified patterns and support/resistance levels to predict the direction of the next candle.

**Comment by karanmanglani** [comment]
I want to work on this issue

**Comment by Arya-Hari** [comment]
Hi! I would love to be assigned this issue! I have a prior experience of two years in ML and I believe I can contribute well to this issue. Thank you!

**Comment by RishabTR** [comment]
@Ayushpanditmoto Hey,there I have completed the model using random forest classifier and scikit learn can i raise an pr?

**Comment by Ayushpanditmoto** [comment]
Yes

**Comment by RishabTR** [comment]
@Ayushpanditmoto  I have created an pr kindly check into it.
