### ISSUE TITLE
Perform Exploratory data analysis and visualizations on the data

### ISSUE THREAD

**Issue by shaziaakhan** [Ayushpanditmoto/Trading-Bot#31]
Hi @Ayushpanditmoto I would like to perform EDA on the datasets and analyze the visualizations. Please assign this to me [GSSoC 24]

**Comment by NakacwaOlivia** [comment]
@shaziaakhan, please continue.

**Comment by shaziaakhan** [comment]
@Ayushpanditmoto pls assign me

**Comment by shaziaakhan** [comment]
can u add labels please
