### ISSUE TITLE
[UI/UX] Create a beautiful button small size 2 button telegram and signup quotex

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/Trading-Bot#4]
![Screenshot_8](https://github.com/Ayushpanditmoto/Trading-Bot/assets/31253617/b0d65c4b-a9db-497e-801d-7c6be8834b3f)

**Comment by SohamPatel0810** [comment]
Please assign it to me

**Comment by Ayushpanditmoto** [comment]
Assigned

**Comment by litesh1123** [comment]
please assign me this issue

**Comment by palayushi293** [comment]
Please assign me this issue 
I am waiting for your response

**Comment by litesh1123** [comment]
@Ayushpanditmoto thank you sir

**Comment by litesh1123** [comment]
@Ayushpanditmoto sir i have designed page with 2 buttons of telegram and sign up quotex but in git code base there is no web dev code shall i create whole page and push it in code base

**Comment by Ayushpanditmoto** [comment]
@litesh1123 we don't want website its python and ml project

**Comment by SohamPatel0810** [comment]
Where do you exactly want the buttons the. Can you please elaborate a bit

**Comment by Ayushpanditmoto** [comment]
in 2 column 1 row

**Comment by Ayushpanditmoto** [comment]
@SohamPatel0810

**Comment by SohamPatel0810** [comment]
In the Readme file only right

**Comment by SohamPatel0810** [comment]
If yes provide can you provide me the link for redirection on click.
Thanks

**Comment by Ayushpanditmoto** [comment]
Currently make that telegram link blank

**Comment by SohamPatel0810** [comment]
And for the signup ?
