### ISSUE TITLE
Past analysis of user's trading history.

### ISSUE THREAD

**Issue by Cralsic123** [Ayushpanditmoto/Trading-Bot#41]
It will show a detailed analysis of the user's past trading analysis and how much he lost and got from his trading history.
I have worked on data analysis on prior projects and I want you to assign me this issue @Ayushpanditmoto

**Comment by merciajeno** [comment]
I have worked with intermediate data analysis projects using the numpy,pandas,seaborn,scikit and matplotlib. Please assign this to me

**Comment by Rishukumarsingh12** [comment]
Hi  @Ayushpanditmoto ,
I have worked with time series data and models in whether forecasting and trading prediction. I have also implemented statistical tests in those projects. So I have better knowledge and experience in time series models and datasets. So I kindly request you to assign me this task.
