### ISSUE TITLE
[Data] Collect Data

### ISSUE THREAD

**Issue by porwalshreyaa** [Ayushpanditmoto/Trading-Bot#5]
#### Requirements-

Candlesticks chart
1 candle is supposed to be of 1 min

Columns-

1. High price 
2. Low price 
3. Closing price 
4. Opening price 
5. Time

**Comment by porwalshreyaa** [comment]
Assign this to me.

**Comment by Ayushpanditmoto** [comment]
You can additional data , which can find in Internet

**Comment by dpkkmr20** [comment]
Can you please assign me this issue.

**Comment by porwalshreyaa** [comment]
I found some minute data, checkout 

[stock-dta-intraday-minute-bar](https://www.kaggle.com/datasets/arashnic/stock-data-intraday-minute-bar)

[stock-price-minute-data](https://www.kaggle.com/datasets/nidhidave705/stock-price-minute-data)

**Comment by Ayushpanditmoto** [comment]
@porwalshreyaa looks great

**Comment by Ayushpanditmoto** [comment]
@dpkkmr20 already assigned you can contribute to other task 🙂

**Comment by Ayushpanditmoto** [comment]
@ridhi-ahuja its really great to see you want to contribute to this project , create a issue and write your task give reason why this things need i will assigned 🙂
