### ISSUE TITLE
Lumibot: Sentiment Analysis Strategy for Backtesting

### ISSUE THREAD

**Issue by shaziaakhan** [Ayushpanditmoto/Trading-Bot#76]
Implementing a backtesting strategy for a trading bot that leverages sentiment analysis to inform buy and sell decisions.

**Functionality:**

- **Backtesting:** Evaluates the strategy's performance using historical data.
- **Sentiment-Based Trading:** Analyzes news headlines to estimate positive or negative sentiment for a chosen stock (default: SPY).

**Process:**

1. **Gathers Sentiment:** Fetches news headlines for the target stock within a specific timeframe.
2. **Estimates Sentiment:** Analyzes the headlines using a custom `estimate_sentiment` function to determine sentiment and its confidence level.
3. **Trading Logic (High Confidence Only):**
   - Only considers trades when the sentiment analysis has extremely high confidence (>0.999)
   - If sentiment is positive and confidence is high:
     - Sells existing holdings if previously bought.
     - Places a buy order with a "bracket order" (including take-profit and stop-loss prices).
   - If sentiment is negative and confidence is high:
     - Sells existing holdings if previously bought.
     - Places a sell order with a bracket order.
4. **Position Sizing:** Allocates a portion of available cash (cash at risk percentage) for each trade.

Pls assign me this issue under GSSoC '24 @Ayushpanditmoto

**Comment by Samik123Mit** [comment]
pls, assign me the issue. I will make sure the task is done.

**Comment by MADHAV0704** [comment]
please assign me this issue

**Comment by mahika-jain** [comment]
hey, could you please assign me this issue, I have an experience with simillar .
