### ISSUE TITLE
Update the Code of Conduct

### ISSUE THREAD

**Issue by Priyanshu2631** [Ayushpanditmoto/Trading-Bot#8]
I want to update the code of conduct file in your project adding the actions or bans which can take place not abiding to the rules thus ensuring a smooth contribution and collaboration without any dissent.

**Comment by SohamPatel0810** [comment]
Please assign it to me

**Comment by akshatsharma2407** [comment]
Hello,I want to update the code of conduct file in your project , please assign it to me

**Comment by akshatsharma2407** [comment]
Hello, I am fully capable of writing the CODE_OF_CONDUCT section as a GSSoC contributor. Kindly assign me this issue as I possess intermediate knowledge of the technology utilized in your project. I am confident that I am the best fit for this task.

**Comment by YuweAEC** [comment]
hey you can assign me this issue i will try my best to write CODE OF CONDUCT under gssoc24
