### ISSUE TITLE
writing README files or tutorials#gssoc24

### ISSUE THREAD

**Issue by pavitraag** [Ayushpanditmoto/Trading-Bot#9]
Keeping in mind that the most important part of a project is its README file, I would like to write README files or tutorials which will help others to get into the project easily.The better the readme file,the better other participants can understand the project

**Comment by hasmithagunda123** [comment]
Hello I am Hasmitha gunda. I m intrested to contribute on this issue. I will serve my best on this .Please assign this to me

**Comment by shaziaakhan** [comment]
Hi im interested in contributing to this issue under GSSoc 2024, please assign this to me.

**Comment by nsk6704** [comment]
I kindly request you to assign this issue to me, an aspiring web developer certified by freeCodeCamp in Web Design and have also interned at a company named Codsoft.

Here is my LinkedIn Profile for more information!

https://www.linkedin.com/in/saketh-kashyap-nagendra/

**Comment by SuhaniStark** [comment]
Hey!! I would like to contribute to this issue please assign me this project...

**Comment by Ayushpanditmoto** [comment]
@SuhaniStark  Start working I am assigning

**Comment by nsk6704** [comment]
Hello @Ayushpanditmoto !

Could you please assign this to me as well!

I have contributed to roadmap.sh's content too which is one of the highest starred repos on GitHub !

**Comment by pavitraag** [comment]
Hello @Ayushpanditmoto ,I have a doubt is there any code available because after knowing how it runs then I can write the README and tutorial file.I could only find the datasets in your github.

**Comment by ArismitaM** [comment]
I would like to enhance the readme file, please assign this project to me
